import type { Metadata } from "next";

import { Header } from "@/components/Layouts/vertical/header/Header";
import { MenuItemsAdmin } from "@/components/Layouts/vertical/sidebar/MenuItems";
import { Sidebar } from "@/components/Layouts/vertical/sidebar/Sidebar";
import { PageWrapper } from "@/components/Layouts/wrapper/PageWrapper";
import { hasAuth } from "@/utils/auth/auth";
import { Box, Container } from "@mui/material";

const perms = ["manage"];
const subject = "all";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Administrador",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await hasAuth(perms, subject);
  return (
    <Box
      sx={{
        display: "flex",
        minHeight: "100vh",
        width: "100%",
      }}
    >
      {/* ------------------------------------------- */}
      {/* Sidebar */}
      {/* ------------------------------------------- */}
      <Sidebar menuItems={MenuItemsAdmin} />

      {/* ------------------------------------------- */}
      {/*  Page Wrapper  */}
      {/* ------------------------------------------- */}
      <PageWrapper>
        <Header />
        {/* ------------------------------------------- */}
        {/*  Navbar  */}
        {/* ------------------------------------------- */}
        {/* <Suspense fallback={<NavbarSkeleton />}>
        <Navbar />
        </Suspense> */}

        <Container sx={{ maxWidth: "100%!important" }}>
          {/* ------------------------------------------- */}
          {/* PageContent */}
          {/* ------------------------------------------- */}
          <Box sx={{ minHeight: "calc(100vh - 170px)" }}>
            {/* <Outlet /> */}
            {children}
            {/* <Index /> */}
          </Box>

          {/* ------------------------------------------- */}
          {/* End Page */}
          {/* ------------------------------------------- */}
        </Container>
      </PageWrapper>
    </Box>
  );
}
